/** Back-compat re-export — prefer @multica/core/room/room-cache */
export {
  scheduleRoomGraphRefresh,
  refreshRoomGraphNow,
  patchRoomGraph,
  patchRoomGraph as patchRoomGraphCache,
  upsertGraphInvocations,
  upsertGraphAssignments,
  upsertGraphMentions,
  patchGraphInvocation,
  patchGraphAssignment,
  appendGraphInvocationEvent,
  upsertGraphDecision,
  roomMessagesInfiniteKey,
  appendRoomMessage,
  appendRoomMessage as appendRoomMessageToInfiniteCache,
  reconcileOptimisticRoomMessage,
  appendOptimisticRoomMessage,
  removeOptimisticRoomMessage,
  patchSendGraphResponse,
} from "./room-cache";
